local L = LibStub("AceLocale-3.0"):NewLocale("GridStatusShield", "enUS", true)

L["[aA]bsorbs.- (%d+) .-damage"] = "[aA]bsorb.- (%d+) .-damage"
L["Aegis detection tolerance"] = "Aegis detection tolerance"
L["Color for shield amount below the low shield threshold."] = "Color for shield amount below the low shield threshold."
L["Color for shield amount below the medium shield threshold."] = "Color for shield amount below the medium shield threshold."
L["Increase this parameter if your Divine Aegis isn't not correctly detected. But can also lead to miss detection the higher the value is."] = "Increase this parameter if your Divine Aegis isn't not correctly detected. But can also lead to miss detection the higher the value is."
L["Low shield color"] = "Low shield color"
L["Low shield threshold"] = "Low shield threshold"
L["Medium shield color"] = "Medium shield color"
L["Medium shield threshold"] = "Medium shield threshold"
L["Shield left"] = "Shield left"
L["The threshold below which a shield is considered low."] = "The threshold below which a shield is considered low."
L["The threshold below which a shield is considered medium."] = "The threshold below which a shield is considered medium."
L["Use combat log"] = "Use combat log"
L["Uses the combat log to detect shields. This can be faster but is also be more inaccurate."] = "Uses the combat log to detect shields. This can be faster but is also be more inaccurate."